development:
  adapter: mysql2
  encoding: utf8
  database: pcstore
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: pcstore_test
  host: localhost
  username: root
  password:

production: